#pragma once
#include <picoio/vm/opcodes_def.hpp>
#include <picoio/vm/variant.hpp>

#include <map>

namespace picoio { namespace vm {
   enum opcodes {
      PICO_VM_CONTROL_FLOW_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_BR_TABLE_OP(PICO_VM_CREATE_ENUM)
      PICO_VM_RETURN_OP(PICO_VM_CREATE_ENUM)
      PICO_VM_CALL_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_CALL_IMM_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_PARAMETRIC_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_VARIABLE_ACCESS_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_MEMORY_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_I32_CONSTANT_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_I64_CONSTANT_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_F32_CONSTANT_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_F64_CONSTANT_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_COMPARISON_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_NUMERIC_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_CONVERSION_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_EXIT_OP(PICO_VM_CREATE_ENUM)
      PICO_VM_EMPTY_OPS(PICO_VM_CREATE_ENUM)
      PICO_VM_ERROR_OPS(PICO_VM_CREATE_ENUM)
   };
   
   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         PICO_VM_CONTROL_FLOW_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_BR_TABLE_OP(PICO_VM_CREATE_MAP)
         PICO_VM_RETURN_OP(PICO_VM_CREATE_MAP)
         PICO_VM_CALL_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_CALL_IMM_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_PARAMETRIC_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_VARIABLE_ACCESS_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_MEMORY_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_I32_CONSTANT_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_I64_CONSTANT_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_F32_CONSTANT_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_F64_CONSTANT_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_COMPARISON_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_NUMERIC_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_CONVERSION_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_EXIT_OP(PICO_VM_CREATE_MAP)
         PICO_VM_EMPTY_OPS(PICO_VM_CREATE_MAP)
         PICO_VM_ERROR_OPS(PICO_VM_CREATE_MAP)
      };
   }; 

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   PICO_VM_CONTROL_FLOW_OPS(PICO_VM_CREATE_CONTROL_FLOW_TYPES)
   PICO_VM_BR_TABLE_OP(PICO_VM_CREATE_BR_TABLE_TYPE)
   PICO_VM_RETURN_OP(PICO_VM_CREATE_CONTROL_FLOW_TYPES)
   PICO_VM_CALL_OPS(PICO_VM_CREATE_CALL_TYPES)
   PICO_VM_CALL_IMM_OPS(PICO_VM_CREATE_CALL_IMM_TYPES)
   PICO_VM_PARAMETRIC_OPS(PICO_VM_CREATE_TYPES)
   PICO_VM_VARIABLE_ACCESS_OPS(PICO_VM_CREATE_VARIABLE_ACCESS_TYPES)
   PICO_VM_MEMORY_OPS(PICO_VM_CREATE_MEMORY_TYPES)
   PICO_VM_I32_CONSTANT_OPS(PICO_VM_CREATE_I32_CONSTANT_TYPE)
   PICO_VM_I64_CONSTANT_OPS(PICO_VM_CREATE_I64_CONSTANT_TYPE)
   PICO_VM_F32_CONSTANT_OPS(PICO_VM_CREATE_F32_CONSTANT_TYPE)
   PICO_VM_F64_CONSTANT_OPS(PICO_VM_CREATE_F64_CONSTANT_TYPE)
   PICO_VM_COMPARISON_OPS(PICO_VM_CREATE_TYPES)
   PICO_VM_NUMERIC_OPS(PICO_VM_CREATE_TYPES)
   PICO_VM_CONVERSION_OPS(PICO_VM_CREATE_TYPES)
   PICO_VM_EXIT_OP(PICO_VM_CREATE_EXIT_TYPE)
   PICO_VM_EMPTY_OPS(PICO_VM_CREATE_TYPES)
   PICO_VM_ERROR_OPS(PICO_VM_CREATE_TYPES)

   using opcode = variant<
      PICO_VM_CONTROL_FLOW_OPS(PICO_VM_IDENTITY)
      PICO_VM_BR_TABLE_OP(PICO_VM_IDENTITY)
      PICO_VM_RETURN_OP(PICO_VM_IDENTITY)
      PICO_VM_CALL_OPS(PICO_VM_IDENTITY)
      PICO_VM_CALL_IMM_OPS(PICO_VM_IDENTITY)
      PICO_VM_PARAMETRIC_OPS(PICO_VM_IDENTITY)
      PICO_VM_VARIABLE_ACCESS_OPS(PICO_VM_IDENTITY)
      PICO_VM_MEMORY_OPS(PICO_VM_IDENTITY)
      PICO_VM_I32_CONSTANT_OPS(PICO_VM_IDENTITY)
      PICO_VM_I64_CONSTANT_OPS(PICO_VM_IDENTITY)
      PICO_VM_F32_CONSTANT_OPS(PICO_VM_IDENTITY)
      PICO_VM_F64_CONSTANT_OPS(PICO_VM_IDENTITY)
      PICO_VM_COMPARISON_OPS(PICO_VM_IDENTITY)
      PICO_VM_NUMERIC_OPS(PICO_VM_IDENTITY)
      PICO_VM_CONVERSION_OPS(PICO_VM_IDENTITY)
      PICO_VM_EXIT_OP(PICO_VM_IDENTITY)
      PICO_VM_EMPTY_OPS(PICO_VM_IDENTITY)
      PICO_VM_ERROR_OPS(PICO_VM_IDENTITY_END)
      >;
}} // namespace picoio::vm
